#!/usr/bin/env python3
"""Generated by android-build-broker v1. Regenerate with: broker.py init-repo REPOSITORY"""

from __future__ import annotations

import argparse
import json
import os
import stat
import subprocess
import sys
import time
import uuid
from pathlib import Path

if sys.version_info < (3, 10):
    raise SystemExit("request-android-build requires Python 3.10 or newer")

# This block is deliberately duplicated from source_identity.py: the installed
# client is standalone and must compute exactly the identity checked by worker.py.
exec(compile('''"""Deterministic identity for a Git HEAD and its non-ignored worktree."""

from __future__ import annotations

import hashlib
import os
import stat
import subprocess
from dataclasses import dataclass


class SourceIdentityError(RuntimeError):
    pass


@dataclass(frozen=True)
class SourceIdentity:
    head: str
    digest: str


def _git(repo: bytes, *args: bytes) -> bytes:
    command = [b"git", b"-C", repo, b"-c", b"core.quotepath=false", *args]
    try:
        result = subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except (OSError, subprocess.CalledProcessError) as exc:
        detail = getattr(exc, "stderr", b"").decode("utf-8", "replace").strip()
        raise SourceIdentityError(detail or f"Git command failed: {args!r}") from exc
    return result.stdout


def _snapshot(repo: bytes) -> tuple[bytes, tuple[bytes, ...]]:
    head = _git(repo, b"rev-parse", b"--verify", b"HEAD").strip()
    if len(head) not in (40, 64) or any(byte not in b"0123456789abcdef" for byte in head):
        raise SourceIdentityError("HEAD is not a canonical object ID")
    raw = _git(repo, b"ls-files", b"-z", b"--cached", b"--others", b"--exclude-standard", b"--")
    paths = tuple(sorted(set(path for path in raw.split(b"\\0") if path)))
    return head, paths


def _field(digest: object, value: bytes) -> None:
    digest.update(len(value).to_bytes(8, "big"))
    digest.update(value)


def compute_source_identity(repo: str | bytes) -> SourceIdentity:
    repo_bytes = os.fsencode(os.path.realpath(repo))
    for _attempt in range(3):
        head, paths = _snapshot(repo_bytes)
        digest = hashlib.sha256(b"android-build-broker-source-v1\\0")
        _field(digest, head)
        unstable = False
        for relative in paths:
            if relative == b".artifacts" or relative.startswith(b".artifacts/"):
                continue
            if relative == b".git" or relative.startswith(b".git/") or relative.startswith(b"/") or b"\\0" in relative:
                raise SourceIdentityError("Git returned an unsafe path")
            full_path = repo_bytes + b"/" + relative
            _field(digest, relative)
            try:
                before = os.lstat(full_path)
            except FileNotFoundError:
                digest.update(b"deleted\\0")
                continue
            if stat.S_ISLNK(before.st_mode):
                digest.update(b"symlink\\0")
                _field(digest, os.readlink(full_path))
                try:
                    unstable = os.lstat(full_path) != before
                except FileNotFoundError:
                    unstable = True
                if unstable:
                    break
                continue
            if not stat.S_ISREG(before.st_mode):
                raise SourceIdentityError(f"Unsupported worktree file type: {os.fsdecode(relative)!r}")
            digest.update(b"100755\\0" if before.st_mode & 0o111 else b"100644\\0")
            flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
            try:
                fd = os.open(full_path, flags)
                with os.fdopen(fd, "rb", closefd=True) as source:
                    opened = os.fstat(source.fileno())
                    if (opened.st_dev, opened.st_ino, opened.st_mode) != (before.st_dev, before.st_ino, before.st_mode):
                        unstable = True
                        break
                    digest.update(before.st_size.to_bytes(8, "big"))
                    while chunk := source.read(1024 * 1024):
                        digest.update(chunk)
                    after = os.fstat(source.fileno())
            except (FileNotFoundError, OSError):
                unstable = True
                break
            stable_fields = ("st_dev", "st_ino", "st_mode", "st_size", "st_mtime_ns", "st_ctime_ns")
            if any(getattr(before, name) != getattr(after, name) for name in stable_fields):
                unstable = True
                break
        if not unstable and _snapshot(repo_bytes) == (head, paths):
            return SourceIdentity(head.decode("ascii"), digest.hexdigest())
    raise SourceIdentityError("Worktree changed while its source identity was computed")
''', "<source_identity>", "exec"))

PROTOCOL_VERSION = 1


def fail(message: str) -> None:
    print(f"request-android-build: {message}", file=sys.stderr)
    raise SystemExit(1)


def atomic_json(path: Path, value: object, exclusive: bool = False) -> None:
    payload = (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode()
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
    fd = os.open(temporary, flags, 0o600)
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, "wb") as output:
            output.write(payload)
            output.flush()
            os.fsync(output.fileno())
        if exclusive:
            try:
                os.link(temporary, path, follow_symlinks=False)
            except FileExistsError:
                fail(f"file already exists: {path}")
            temporary.unlink()
        else:
            os.replace(temporary, path)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def repository_root() -> Path:
    result = subprocess.run(["git", "rev-parse", "--show-toplevel"], text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode:
        fail("run this command inside a Git repository")
    return Path(result.stdout.strip()).resolve()


def broker_heartbeat(repository: Path) -> dict[str, object]:
    root = repository / ".artifacts" / "android"
    heartbeat_path = root / "heartbeat.json"
    try:
        heartbeat = json.loads(heartbeat_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"no running broker heartbeat: {exc}")
    now = int(time.time())
    expected = {"protocolVersion", "brokerSessionId", "targetRepository", "pid", "updatedAt"}
    if type(heartbeat) is not dict or set(heartbeat) != expected:
        fail("invalid broker heartbeat")
    session = heartbeat.get("brokerSessionId")
    if type(session) is not str or type(heartbeat.get("updatedAt")) is not int or now - heartbeat["updatedAt"] > 5 or heartbeat["updatedAt"] > now + 30:
        fail("broker heartbeat is stale")
    if heartbeat.get("targetRepository") != str(repository):
        fail("broker heartbeat targets a different repository")
    return heartbeat


def main() -> None:
    parser = argparse.ArgumentParser(description="Request an Android build from the local broker")
    parser.add_argument("--broker-status", action="store_true", help="report whether this repository's broker is running without requesting a build")
    args = parser.parse_args()
    repository = repository_root()
    heartbeat = broker_heartbeat(repository)
    if args.broker_status:
        print(json.dumps({
            "running": True,
            "brokerSessionId": heartbeat["brokerSessionId"],
            "pid": heartbeat["pid"],
            "updatedAt": heartbeat["updatedAt"],
        }, separators=(",", ":")))
        return
    root = repository / ".artifacts" / "android"
    now = int(time.time())
    session = heartbeat["brokerSessionId"]
    identity = compute_source_identity(repository)
    request_id = str(uuid.uuid4())
    requests = root / "requests"
    result_dir = root / "results" / request_id
    for directory in (root, requests, root / "claimed", root / "results", result_dir):
        directory.mkdir(mode=0o700, parents=True, exist_ok=True)
        info = directory.lstat()
        if not stat.S_ISDIR(info.st_mode) or stat.S_ISLNK(info.st_mode) or info.st_uid != os.geteuid() or info.st_mode & 0o022:
            fail(f"unsafe runtime directory: {directory}")
    status_path = result_dir / "status.json"
    atomic_json(status_path, {"protocolVersion": 1, "requestId": request_id, "state": "queued", "updatedAt": now}, exclusive=True)
    request = {
        "protocolVersion": PROTOCOL_VERSION,
        "requestId": request_id,
        "createdAt": now,
        "brokerSessionId": session,
        "head": identity.head,
        "worktreeDigest": identity.digest,
    }
    atomic_json(requests / f"{request_id}.json", request, exclusive=True)
    print(json.dumps({"requestId": request_id, "statusPath": str(status_path.relative_to(repository))}, separators=(",", ":")))


if __name__ == "__main__":
    main()
