#!/usr/bin/env python3
"""Generated by ios-build-broker v1. Regenerate with: broker.py init-repo REPOSITORY"""

from __future__ import annotations

import argparse
import json
import os
import stat
import subprocess
import sys
import time
import uuid
from pathlib import Path

if sys.version_info < (3, 10):
    raise SystemExit("request-ios-smoke requires Python 3.10 or newer")

exec(compile('''"""Identity of Git HEAD and all tracked/non-ignored worktree inputs."""

from __future__ import annotations

import hashlib
import os
import stat
import subprocess
from dataclasses import dataclass


class SourceIdentityError(RuntimeError):
    pass


@dataclass(frozen=True)
class SourceIdentity:
    head: str
    digest: str


def _git(repo: bytes, *args: bytes) -> bytes:
    try:
        return subprocess.run([b"git", b"-C", repo, b"-c", b"core.quotepath=false", *args], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE).stdout
    except (OSError, subprocess.CalledProcessError) as exc:
        detail = getattr(exc, "stderr", b"").decode("utf-8", "replace").strip()
        raise SourceIdentityError(detail or "Git command failed") from exc


def _snapshot(repo: bytes) -> tuple[bytes, tuple[bytes, ...]]:
    head = _git(repo, b"rev-parse", b"--verify", b"HEAD").strip()
    if len(head) not in (40, 64) or any(byte not in b"0123456789abcdef" for byte in head):
        raise SourceIdentityError("HEAD is not a canonical object ID")
    raw = _git(repo, b"ls-files", b"-z", b"--cached", b"--others", b"--exclude-standard", b"--")
    return head, tuple(sorted(set(path for path in raw.split(b"\\0") if path)))


def _field(digest: Any, value: bytes) -> None:
    digest.update(len(value).to_bytes(8, "big"))
    digest.update(value)


def compute_source_identity(repo: str | bytes) -> SourceIdentity:
    repo_bytes = os.fsencode(os.path.realpath(repo))
    for _ in range(3):
        head, paths = _snapshot(repo_bytes)
        digest = hashlib.sha256(b"ios-build-broker-source-v1\\0")
        _field(digest, head)
        unstable = False
        for relative in paths:
            if relative == b".artifacts" or relative.startswith(b".artifacts/"):
                continue
            if relative == b".git" or relative.startswith(b".git/") or relative.startswith(b"/"):
                raise SourceIdentityError("Git returned an unsafe path")
            full = repo_bytes + b"/" + relative
            _field(digest, relative)
            try:
                before = os.lstat(full)
            except FileNotFoundError:
                digest.update(b"deleted\\0")
                continue
            if stat.S_ISLNK(before.st_mode):
                digest.update(b"symlink\\0")
                _field(digest, os.readlink(full))
                try:
                    unstable = os.lstat(full) != before
                except FileNotFoundError:
                    unstable = True
            elif stat.S_ISREG(before.st_mode):
                digest.update(b"100755\\0" if before.st_mode & 0o111 else b"100644\\0")
                try:
                    fd = os.open(full, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0))
                    with os.fdopen(fd, "rb") as source:
                        opened = os.fstat(source.fileno())
                        if (opened.st_dev, opened.st_ino, opened.st_mode) != (before.st_dev, before.st_ino, before.st_mode):
                            unstable = True
                            break
                        digest.update(before.st_size.to_bytes(8, "big"))
                        while chunk := source.read(1024 * 1024):
                            digest.update(chunk)
                        after = os.fstat(source.fileno())
                    fields = ("st_dev", "st_ino", "st_mode", "st_size", "st_mtime_ns", "st_ctime_ns")
                    unstable = any(getattr(before, field) != getattr(after, field) for field in fields)
                except OSError:
                    unstable = True
            else:
                raise SourceIdentityError(f"Unsupported worktree file type: {os.fsdecode(relative)!r}")
            if unstable:
                break
        if not unstable and _snapshot(repo_bytes) == (head, paths):
            return SourceIdentity(head.decode("ascii"), digest.hexdigest())
    raise SourceIdentityError("Worktree changed while its source identity was computed")
''', "<source_identity>", "exec"))

PROTOCOL_VERSION = 1
PROFILE_ID = 'trene'
ALLOWED_FLOWS = ('damaged-backup', 'newer-backup', 'picker-cancellation', 'restore-failure', 'restore-success', 'rollback-failure', 'share-cancellation', 'storage-failure')
UUID_PATTERN = __import__("re").compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")


def fail(message: str) -> None:
    print(f"request-ios-smoke: {message}", file=sys.stderr)
    raise SystemExit(1)


def atomic_json(path: Path, value: object, exclusive: bool = False) -> None:
    payload = (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode()
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0), 0o600)
    try:
        with os.fdopen(fd, "wb") as output:
            os.fchmod(output.fileno(), 0o600)
            output.write(payload)
            output.flush()
            os.fsync(output.fileno())
        if exclusive:
            os.link(temporary, path, follow_symlinks=False)
            temporary.unlink()
        else:
            os.replace(temporary, path)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def repository_root() -> Path:
    result = subprocess.run(["git", "rev-parse", "--show-toplevel"], text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode:
        fail("run this command inside a Git repository")
    return Path(result.stdout.strip()).resolve()


def heartbeat(repository: Path) -> dict[str, object]:
    try:
        value = json.loads((repository / ".artifacts/ios-broker/heartbeat.json").read_text())
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"no running broker heartbeat: {exc}")
    expected = {"protocolVersion", "brokerSessionId", "profileId", "targetRepository", "pid", "updatedAt"}
    now = int(time.time())
    if type(value) is not dict or set(value) != expected:
        fail("invalid broker heartbeat")
    if value["protocolVersion"] != PROTOCOL_VERSION:
        fail("unsupported broker protocol")
    if value["profileId"] != PROFILE_ID:
        fail("broker heartbeat uses a different project profile")
    if type(value["brokerSessionId"]) is not str or not UUID_PATTERN.fullmatch(value["brokerSessionId"]):
        fail("invalid broker heartbeat session")
    if type(value["pid"]) is not int or value["pid"] <= 0:
        fail("invalid broker heartbeat PID")
    if type(value["updatedAt"]) is not int or now - value["updatedAt"] > 5 or value["updatedAt"] > now + 30:
        fail("broker heartbeat is stale")
    if value["targetRepository"] != str(repository):
        fail("broker heartbeat targets a different repository")
    return value


def main() -> None:
    parser = argparse.ArgumentParser(description="Request an allowlisted iOS smoke flow")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--broker-status", action="store_true")
    group.add_argument("--flow", choices=ALLOWED_FLOWS)
    args = parser.parse_args()
    repository = repository_root()
    broker = heartbeat(repository)
    if args.broker_status:
        print(json.dumps({"running": True, "profileId": PROFILE_ID, "brokerSessionId": broker["brokerSessionId"], "pid": broker["pid"], "updatedAt": broker["updatedAt"]}, separators=(",", ":")))
        return
    root = repository / ".artifacts/ios-broker"
    request_id = str(uuid.uuid4())
    result_dir = root / "results" / request_id
    identity = compute_source_identity(repository)
    for directory in (root, root / "requests", root / "claimed", root / "results", result_dir):
        directory.mkdir(mode=0o700, parents=True, exist_ok=True)
        info = directory.lstat()
        if not stat.S_ISDIR(info.st_mode) or stat.S_ISLNK(info.st_mode) or info.st_uid != os.geteuid() or info.st_mode & 0o022:
            fail(f"unsafe runtime directory: {directory}")
    now = int(time.time())
    status_path = result_dir / "status.json"
    atomic_json(status_path, {"protocolVersion": 1, "requestId": request_id, "state": "queued", "updatedAt": now}, exclusive=True)
    atomic_json(root / "requests" / f"{request_id}.json", {
        "protocolVersion": 1, "requestId": request_id, "createdAt": now,
        "brokerSessionId": broker["brokerSessionId"], "head": identity.head,
        "worktreeDigest": identity.digest, "flow": args.flow,
    }, exclusive=True)
    print(json.dumps({"requestId": request_id, "statusPath": str(status_path.relative_to(repository))}, separators=(",", ":")))


if __name__ == "__main__":
    main()
